{{- if .Values.ui.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ui.ingress.className }}
spec:
  controller: ingress.k8s.aws/alb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowler-ui-ingress
  labels:
    {{- include "prowler-api.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ui.ingress.className }}
  rules:
  {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service }}
                port:
                  number: {{ .backend.port }}
        {{- end }}
  {{- end }}
{{- end }}