{{- if and (index .Values "external-secrets" "enabled") .Values.ui.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowler-ui-env
spec:
  refreshInterval: {{ .Values.ui.env.refreshInterval | default "30m" }}
  secretStoreRef:
    name: {{ .Values.ui.env.secretStoreRef.name | default "secretstore-prowler" }}
    kind:  SecretStore
  target:
    name: {{ .Values.ui.env.targetSecretName | default "prowler-ui-env" }}
    creationPolicy: Owner
  data:
  {{- range .Values.ui.env.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.ui.env.remoteRef }}
      property: {{ . }}
  {{- end }}
{{- end }}