{{- if and (index .Values "external-secrets" "enabled") .Values.ProwlerApi.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowler-api-env
spec:
  refreshInterval: {{ .Values.env.refreshInterval | default "30m" }}
  secretStoreRef:
    name: {{ .Values.env.secretStoreRef.name | default "secretstore-prowler" }}
    kind:  SecretStore
  target:
    name: {{ .Values.env.targetSecretName | default "prowler-api-env" }}
    creationPolicy: Owner
  data:
  {{- range .Values.env.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.env.remoteRef }}
      property: {{ . }}
  {{- end }}
{{- end }}