{{- if index .Values "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-prowler
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ default (include "prowler-api.serviceAccountName" .) .Values.secretStore.aws.serviceAccount }}
{{- end }}