# StorageClass for prowler-api
{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Delete" }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  encrypted: "true"
{{- end }}