apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-ui
  labels:
    {{- include "prowler-api.labels" . | nindent 4 }}
    app: prowler-ui
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prowler-api.selectorLabels" . | nindent 6 }}
      app: prowler-ui
  template:
    metadata:
      annotations:
      {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowler-api.labels" . | nindent 8 }}
        app: prowler-ui
    spec:
      serviceAccountName: {{ include "prowler-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: prower-ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag}}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: prowler-ui-env
          command:
            {{- toYaml .Values.ui.command | nindent 12 }}
          {{- if .Values.ui.ports }}
          ports:
            {{- toYaml .Values.ui.ports | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.ui.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ui.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
