apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-api-worker
  labels:
    app: prowler-api-worker
    {{- include "prowler-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: prowler-api-worker
      {{- include "prowler-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowler-api.labels" . | nindent 8 }}
        app: prowler-api-worker
    spec:
      serviceAccountName: {{ include "prowler-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag}}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: prowler-api-env
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          {{- if .Values.worker.ports }}
          ports:
            {{- toYaml .Values.worker.ports | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.worker.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "prowler-api.fullname" $ }}-config
              mountPath: {{ $.Values.releaseConfigRoot }}{{ $.Values.releaseConfigPath }}
              subPath: config.yaml
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: {{ include "prowler-api.fullname" . }}-config
          configMap:
            name: {{ include "prowler-api.fullname" . }}-config
      {{- with .Values.worker.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
